title:            anya's little textbook
longtitle:        anya's little textbook
author:           anya
description: >
  Build Jekyll site with the GitBook style.

version:          1.0
gitbook_version:  3.2.3

# url:              'https://sighingnow.github.io'
# baseurl:          '/jekyll-gitbook'
# rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook


nav:
  - title: anya's little textbook
    url: /
  - title: study guides
    url: /study-guides.md/
  - title: summer research
    url: /summer-research.md/
  - title: applying for grad school
    url: /applying-for-grad-school/
    sublinks:
      - title: introduction
        url: /applying-for-grad-school/introduction.md/
      - title: phd vs master's
        url: /applying-for-grad-school/phd-vs-masters/
      - title: affording a phd
        url: /applying-for-grad-school/affording-a-phd/
      - title: sample timeline
        url: /applying-for-grad-school/sample-timeline/
      - title: picking schools
        url: /applying-for-grad-school/picking-schools/
      - title: recommendation letters
        url: /applying-for-grad-school/recommendation-letters/
      - title: transcripts
        url: /applying-for-grad-school/transcripts/
      - title: statement of purpose
        url: /applying-for-grad-school/statement-of-purpose/
      - title: personal statement
        url: /applying-for-grad-school/personal-statement/
      - title: cv
        url: /applying-for-grad-school/cv/
      - title: fee waivers
        url: /applying-for-grad-school/fee-waivers/
      - title: contacting professors
        url: /applying-for-grad-school/contacting-professors/
      - title: interviews
        url: /applying-for-grad-school/interviews/
      - title: fellowships
        url: /applying-for-grad-school/fellowships/
      - title: international fellowships
        url: /applying-for-grad-school/campus-visits/
      - title: campus visits
        url: /applying-for-grad-school/campus-visits/

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
